name: Envek
markdown: kramdown
highlighter: pygments
exclude:
  - Gemfile
  - Rakefile
include:
  - .well-known
encoding: UTF-8

permalink: /:categories/:year/:month/:day/:title

defaults:
  - scope:
      path: en
    values:
      layout: blog.en
      lang: en
  - scope:
      path: ru
    values:
      layout: blog.ru
      lang: ru
  - scope:
      path: ja
    values:
      layout: blog.ja
      lang: ja

languages:
  en: English
  ru: Русский
  ja: 日本語

disqus_id: envek

google_adsense:
  client_id: ca-pub-8719910245442223
  slot: 4805107393
